stages:
  - build
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - master

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - smew
  script:
    - chmod og= $SMEW_ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $SMEW_ID_RSA -o StrictHostKeyChecking=no $SMEW_SERVER_USER@$SMEW_SERVER_IP "docker  login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY && docker pull $TAG_COMMIT"
    - ssh -i $SMEW_ID_RSA -o StrictHostKeyChecking=no $SMEW_SERVER_USER@$SMEW_SERVER_IP "docker container rm -f amplify || true"
    - ssh -i $SMEW_ID_RSA -o StrictHostKeyChecking=no $SMEW_SERVER_USER@$SMEW_SERVER_IP "docker run -d -p 8002:80 --name amplify --network smew.network $TAG_COMMIT"
  environment:
    name: production
    url: http://amplify.inkbird.io
  only:
    - master